language: node_js
node_js: 12.15.0
services:
    - docker
install:
    - npm install
script:
    - npm run lint
    - npm run build
deploy:
    provider: script
    skip_cleanup: true
    on:
        branch: master
    script:
        - npm run release
cache:
    directories:
        - node_modules
notifications:
    webhooks:
        urls:
            # 钉钉
            - secure: pCBLuzxjzjdLTHZhse4z66lQJsyrklML1lPfwZSQfgBJLMteyrY9bXqH0uXxzw7UpnFvFQRZjOanDQh+78M1U43PoXzGzONcRc8FTMOSGgCiLd7w7ZNaKaBP+uCzvnS2Y0uHZpZcb0QxCvLTBMQGpO6NztcDTYAoVmWtok0/IwNdHI45Bh4kefNT5L9WE2M09R9J7dLI42feHzNyf7iSHEEJTOi7V5v++FdnRzdA+Vy/UtESpN4RviAJ4E/FXMQhuJ6ili9w/P4qPBJyMTtn9XxRmkSXP+UIwWNoojl/UcbnAKFVywcQzQkyfqe4grz1xmeyoSDX/PopMwpok+/N7pBY4/UWz8k16GlISOifME5MfZ/SHhP5BS/yYV5Pih8iHwMaM0gqXIo2nuBVdBF7pB3058zbIovM0v2FSg3wV2z+4PLeS4UsWaxt5Iqpq0YoWvkOmCMB8aqP1acqCKplkqNw3sU3WJ7mIU8xTd9U5PPYGHeF86h+BLMdz8nYHI8n8n1muKUMaW8MZ4G7jLlOX31Fx07VVjAOAhj0rWAz9qVOKjZFhFh+HmaBgY84zR6zQzZnNtD42vsaNrbKkXsOIrc7cSDdAkkM/7xUeOl+Y0Inr5ElALTpKz5oem7P0M1AN2Z/IAYVYuI9Sre0uFEsbnPbGZ54c7s5/k2r4WFztMk=
            # jenkins
            # - secure: oZE62QGHqTgV+/zjVwZfIsIy7CPh87NNUsfXw+1H0mvNn/P1GYOc/EDwsuWafUC52rK+5Xr8JoCAhepJyeHYH7nCJNAuuRSTQ6Foib1JyL+8QCO7SS5xa5q9yMb437jxThAl4AMyNOxbrlMRdb8SrpedeLyyND4nz4PKmYRVgWck3w3hpaou8s3nVDjBBwroPMa839vI5omuUB7XEfslpu6v3GAJluLVEDVTRmsbplJj+7LFce2w5E5zjppzxiQxUf9Mn5NlciXF/Zq3Qf/h545LuhbJXTBWWbUTVC8g1A+hghBuBbPDRnwljBJK4x3JmwXMxGQAi4v7VqMOj2KAamB3+NZcRUc5cBEMauD5qv8CiUWxqmmXfJdRR8EIKY4SqU+dIKobqMzRHQgNbEyzwwICrGYOj8w0Zf89la6e8fdUySLszWLcuLnZ2NsoJwdR8tONoPliCsQCx+sZpSXl47vKTsHOfqwhQj79jrTFlLyfFVCuDgeKQvDNY7iqDJO+EgUUz36YnksjcthMYprzBihfK1tOmRIEsbgM3p4Q1iWWD/lhkRct/80ZWqJYj6py+CJBcsAo0g33/Lev0SP5IXTmiVq7mxKA9XyPc799sIUKoCTZIXcGYnwHpx1+p6KwKnsQPdEdyOB+yHkVia/eLM31XsBO4xdUORqQRVDmiK0=
