language: node_js
node_js: 12

services:
    - docker

install:
    - npm install
script:
    - npm run build
    - npm run docs:changelog
    - npm run docs:build

deploy:
    provider: script
    skip_cleanup: true
    on:
        branch: master
    script:
        - npm run release
cache:
    directories:
        - node_modules
notifications:
    webhooks:
        urls:
            - "https://oapi.dingtalk.com/robot/send?access_token=${DINGTALK_ACCESS_TOKEN}"
            - "${JENKINS_WEBHOOKS}"
