language: node_js
node_js: 12
services:
    - docker
install:
    - npm install
script:
    - npm run build
    - npm run docs:changelog
    - npm run docs:build
deploy:
    provider: script
    skip_cleanup: true
    on:
        branch: master
    script:
        - npm run release
cache:
    directories:
        - node_modules
notifications:
    webhooks:
        urls:
            - secure: Y7K4gBxOdKBohPuERhpIRBvHhUBTPXnQ6oLZB2P1gxw3G1F8yYzx5HH3OEsge4WEFBEYBXbSUmijSTHRiLD3sx6iDDcqEov86fWUV6d+IIcRXOye4TI5KaR13exqriQK91AVlmyCr2l7jBM83MGkSpzxBJyu2UheK0FgLsGLObRv4Qz6/PNUdZqeBrAKH0YiY7xl/ZzEBFGF0oGppnWUT8P990qeTQsB9NxKeu06s7ngAElLfvxnwViyGXBIjZnv1JdGFvygu9jf34CTVPaWGib3a2OyRimvcBTKOU48sCWg/05UwXo2gXsRGHlclLSSbEMDZ6DESDzrvS825DhgqJGlbrmuC1YF+KusNAqMgL0eBKFNXR57xuBCGWms9xIEg0qfBlWmclWAWUBE4lPPN1kz+/+riVVL08sFHsZ02c2LSQk3wmbSplHU8M0s+F9Pl2UyKwesK8Ak/GGVm3o+eVeq2VYDVZwfTV5FhCq34/RGTAqcGWgzlTUjKDVz3RaW9LlgcN749UMIaFxm8mBD0a2WalFazSksUogge0LypdaEAX9hWBs1J+Yaz/sn5uvgWTFqKPVwwpHYlFx3tnuq4qfdvSJiaDN/g9jv29+/fCHac//yi8pKi8JSpA73Fd3pjnv0S00kcFV3AxHVlA/jDxACqUMHzANqRZdliaeUaZw=
            - secure: JNUVlKUGZXwICxNX4xOmHIfc7eENdjWhp8Ems7g9mQom03tkdlVGbUTsGm9SI5CdO5ySdOgbiYEpaO/gKhZXrmqO180+kuqvSWceR0EWOxbJBMTU14V21ONQQZnVUlpdrhHBAmghinpRXpnaZWFERUyzWOCoKnp6r9qURDV4BF6PLDIJ1dR7ldtUdfBg1ifEtBAvk3+j8v1U04QLT/l42aY6jsT068CzulknCtZDGjlDcJmXbu3LUKW/+sZ8lCPl+Fex/EeTr/n2Eihn2t65BqPNFGgPPbu4B9WhNJ6Bwc8iH5oKLFzSP+eMMNZA/0pKp+wpkdHxZRTLsNbPsPjOVpWQqnDE4V9M+GYdN/0XKqrU7uR2crC4fiFo9nPbU6eDgeLRDDgsVEmqARNJ1KIY66c31gD/rkwOeJQLhPHMydLNr26Yymqkw8RrobqerveJxG1pmSoe2P5tCIvbVeGFkh01NT6mp+XYpV9JyTZ7ZenvsCkkbPgR1PZ0a9sBWPll/lU6+DkJOV8gcN8eKFi23hAiKNuKvTkoQSKFkO0ErqsQNHktuJ3py8Nf4daeukGyhDzCSDjge+J2GC8hiIfuP8qrXcIiUSE7vYOnWJv58TaR/F51uYb7BObJOhGtUtPICcLHIxKeD8vsTsRHvXgy2BcWTZou+l0waisxJLh784E=
