version: "3"

services:
    super-search-hub:
        image: caomeiyouren/super-search-hub
        restart: always
        ports:
            - "8080:80"
        environment:
            PORT: 80
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: "redis://redis:6379/"
            REDIS_HOST: "redis"
            REDIS_PORT: 6379
        depends_on:
            - redis
    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data
volumes:
    redis-data:
