version: "3"

services:
    super-search-hub:
        container_name: super-search-hub-container
        build: .
        restart: always
        ports:
            - "4365:4365"
        environment:
            PORT: 4365
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: "redis://redis:6379/"
            REDIS_HOST: "redis"
            REDIS_PORT: 6379
        depends_on:
            - redis
    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data
volumes:
    redis-data:
